package com.example.ikyky.preprocessing

import com.example.ikyky.core.ml.preprocessing.RecognitionFaceCrop
import com.example.ikyky.core.model.BoundingBox
import com.example.ikyky.core.model.DetectedFace
import com.example.ikyky.core.model.Landmark
import com.example.ikyky.core.model.LandmarkType
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import kotlin.math.cos
import kotlin.math.hypot
import kotlin.math.sin

/**
 * Phase 6E — the 5-point recognition crop.
 *
 * This is the single highest-risk component of the port: a swapped eye mapping
 * produces a horizontally mirrored transform that silently degrades every
 * embedding with no error anywhere. Several tests here exist specifically to
 * fail if that swap is ever reintroduced.
 *
 * The numeric expectations are GOLDEN VALUES generated by the frozen Python
 * reference (`ikyky_lab/preprocessing/align.py::_umeyama`) on the same inputs.
 */
class RecognitionFaceCropTest {

    private val tpl = RecognitionFaceCrop.ARCFACE_TEMPLATE_112

    // -- helpers -------------------------------------------------------------

    /**
     * Builds a face whose landmarks are placed by VIEWER position.
     *
     * Labels follow the convention MEASURED on device (235/235 detections):
     * ML Kit's `LEFT_EYE` lands at the smaller x. Because slots are resolved by
     * position rather than by label, the labelling here only affects which name
     * carries which point — never the resulting geometry (see
     * `theOppositeLabelConventionProducesTheSameGeometry`).
     */
    private fun face(
        viewerLeftEye: Pair<Float, Float>,
        viewerRightEye: Pair<Float, Float>,
        nose: Pair<Float, Float>,
        viewerLeftMouth: Pair<Float, Float>,
        viewerRightMouth: Pair<Float, Float>,
        box: BoundingBox = BoundingBox(380, 270, 530, 440),
    ) = DetectedFace(
        boundingBox = box,
        landmarks = listOf(
            Landmark(LandmarkType.LEFT_EYE, viewerLeftEye.first, viewerLeftEye.second),
            Landmark(LandmarkType.RIGHT_EYE, viewerRightEye.first, viewerRightEye.second),
            Landmark(LandmarkType.NOSE_BASE, nose.first, nose.second),
            Landmark(LandmarkType.MOUTH_LEFT, viewerLeftMouth.first, viewerLeftMouth.second),
            Landmark(LandmarkType.MOUTH_RIGHT, viewerRightMouth.first, viewerRightMouth.second),
        ),
    )

    /** The same physical face labelled the OTHER way (subject-relative). */
    private fun subjectRelativeFace() = DetectedFace(
        boundingBox = BoundingBox(380, 270, 530, 440),
        landmarks = listOf(
            Landmark(LandmarkType.RIGHT_EYE, 412.3f, 301.7f),
            Landmark(LandmarkType.LEFT_EYE, 498.1f, 296.4f),
            Landmark(LandmarkType.NOSE_BASE, 452.0f, 352.9f),
            Landmark(LandmarkType.MOUTH_RIGHT, 419.8f, 404.2f),
            Landmark(LandmarkType.MOUTH_LEFT, 489.5f, 399.1f),
        ),
    )

    private fun realisticFace() = face(
        viewerLeftEye = 412.3f to 301.7f,
        viewerRightEye = 498.1f to 296.4f,
        nose = 452.0f to 352.9f,
        viewerLeftMouth = 419.8f to 404.2f,
        viewerRightMouth = 489.5f to 399.1f,
    )

    private fun arr(vararg p: Pair<Double, Double>) =
        Array(p.size) { doubleArrayOf(p[it].first, p[it].second) }

    // =======================================================================
    // TEMPLATE
    // =======================================================================

    @Test
    fun template_isTheCanonicalArcFaceTemplate_viewerLeftFirst() {
        // Do NOT "fix" these numbers. They are the template the MobileFaceNet /
        // ArcFace model family was trained against; the model's expected input
        // geometry is fixed by its training data.
        assertEquals(38.2946, tpl[0][0], 1e-9)
        assertEquals(51.6963, tpl[0][1], 1e-9)
        assertEquals(73.5318, tpl[1][0], 1e-9)
        assertEquals(51.5014, tpl[1][1], 1e-9)
        assertEquals(56.0252, tpl[2][0], 1e-9)
        assertEquals(71.7366, tpl[2][1], 1e-9)
        assertEquals(41.5493, tpl[3][0], 1e-9)
        assertEquals(92.3655, tpl[3][1], 1e-9)
        assertEquals(70.7299, tpl[4][0], 1e-9)
        assertEquals(92.2041, tpl[4][1], 1e-9)
    }

    @Test
    fun template_slot0IsLeftOfSlot1_andSlot3IsLeftOfSlot4() {
        // The viewer-left-first ordering, verified in Phase 5I on 200 real
        // detections (kps[0].x < kps[1].x in 100.0% of cases).
        assertTrue("eye slots must be viewer-left first", tpl[0][0] < tpl[1][0])
        assertTrue("mouth slots must be viewer-left first", tpl[3][0] < tpl[4][0])
    }

    @Test
    fun templateScalesLinearlyWithOutputSize() {
        val t224 = RecognitionFaceCrop.templateFor(224)
        for (i in 0 until 5) {
            assertEquals(tpl[i][0] * 2.0, t224[i][0], 1e-9)
            assertEquals(tpl[i][1] * 2.0, t224[i][1], 1e-9)
        }
    }

    // =======================================================================
    // LANDMARK MAPPING — the dangerous part
    // =======================================================================

    @Test
    fun requiredLandmarksAreTheFiveTheTemplateNeeds() {
        assertEquals(
            listOf(
                LandmarkType.LEFT_EYE, LandmarkType.RIGHT_EYE, LandmarkType.NOSE_BASE,
                LandmarkType.MOUTH_LEFT, LandmarkType.MOUTH_RIGHT,
            ),
            RecognitionFaceCrop.REQUIRED_LANDMARKS,
        )
    }

    @Test
    fun slotsAreResolvedByMeasuredPosition_notByLabel() {
        // An on-device survey of 235 real detections found ML Kit's LEFT_EYE at
        // the SMALLER x in 235/235 cases, contradicting the subject-relative
        // reading the Phase 5I spec assumed. Slots are therefore assigned by
        // measurement, which is correct under EITHER convention.
        //
        // Here LEFT_EYE sits at the smaller x, so it must win slot 0
        // (viewer-left) even though its NAME suggests the opposite.
        val p = RecognitionFaceCrop.orderedLandmarks(realisticFace())!!
        assertEquals(412.3, p[RecognitionFaceCrop.VIEWER_LEFT_EYE][0], 1e-4)
        assertEquals(498.1, p[RecognitionFaceCrop.VIEWER_RIGHT_EYE][0], 1e-4)
        assertEquals(419.8, p[RecognitionFaceCrop.VIEWER_LEFT_MOUTH][0], 1e-4)
        assertEquals(489.5, p[RecognitionFaceCrop.VIEWER_RIGHT_MOUTH][0], 1e-4)
    }

    @Test
    fun theOppositeLabelConventionProducesTheSameGeometry() {
        // The same physical face under the other naming convention. Because
        // slots are measured, the ordered points are IDENTICAL — this is what
        // makes the port robust to the convention ambiguity rather than
        // dependent on guessing it right.
        val a = RecognitionFaceCrop.orderedLandmarks(realisticFace())!!
        val b = RecognitionFaceCrop.orderedLandmarks(subjectRelativeFace())!!
        for (i in 0 until 5) {
            assertEquals(a[i][0], b[i][0], 1e-9)
            assertEquals(a[i][1], b[i][1], 1e-9)
        }
    }

    @Test
    fun orderedPointsAlwaysComeOutViewerLeftFirst() {
        val p = RecognitionFaceCrop.orderedLandmarks(realisticFace())!!
        assertTrue(
            "slot 0 must be viewer-left",
            p[RecognitionFaceCrop.VIEWER_LEFT_EYE][0] < p[RecognitionFaceCrop.VIEWER_RIGHT_EYE][0],
        )
        assertTrue(
            "slot 3 must be viewer-left",
            p[RecognitionFaceCrop.VIEWER_LEFT_MOUTH][0] < p[RecognitionFaceCrop.VIEWER_RIGHT_MOUTH][0],
        )
    }

    @Test
    fun orderedLandmarks_isNullWhenAnyOfTheFiveIsMissing() {
        for (missing in RecognitionFaceCrop.REQUIRED_LANDMARKS) {
            val f = realisticFace()
            val stripped = f.copy(landmarks = f.landmarks.filter { it.type != missing })
            assertNull("must not align without $missing", RecognitionFaceCrop.orderedLandmarks(stripped))
        }
    }

    @Test
    fun orderedLandmarks_isNullOnNonFiniteCoordinates() {
        val f = realisticFace()
        val broken = f.copy(
            landmarks = f.landmarks.map {
                if (it.type == LandmarkType.NOSE_BASE) it.copy(x = Float.NaN) else it
            },
        )
        assertNull(RecognitionFaceCrop.orderedLandmarks(broken))
    }

    // =======================================================================
    // MIRROR SAFETY — the failure mode the brief calls out
    // =======================================================================

    @Test
    fun swappingOnlyTheEyeLabels_cannotChangeTheResult() {
        // Exchanging two landmarks' LABELS while their POSITIONS stay put must be
        // a no-op. This is precisely the mirrored-crop failure mode the brief
        // warns about; resolving slots by measurement makes it impossible rather
        // than merely detectable.
        val f = realisticFace()
        val swapped = f.copy(
            landmarks = f.landmarks.map {
                when (it.type) {
                    LandmarkType.LEFT_EYE -> it.copy(type = LandmarkType.RIGHT_EYE)
                    LandmarkType.RIGHT_EYE -> it.copy(type = LandmarkType.LEFT_EYE)
                    LandmarkType.MOUTH_LEFT -> it.copy(type = LandmarkType.MOUTH_RIGHT)
                    LandmarkType.MOUTH_RIGHT -> it.copy(type = LandmarkType.MOUTH_LEFT)
                    else -> it
                }
            },
        )
        val m1 = RecognitionFaceCrop.transformFor(f, 112)!!
        val m2 = RecognitionFaceCrop.transformFor(swapped, 112)!!
        assertEquals(m1.a, m2.a, 1e-12)
        assertEquals(m1.b, m2.b, 1e-12)
        assertEquals(m1.tx, m2.tx, 1e-9)
        assertEquals(m1.ty, m2.ty, 1e-9)
        assertTrue("still never a mirror", m2.determinant > 0.0)
    }

    @Test
    fun aGenuinelyMirroredFace_stillYieldsAProperNonReflectingTransform() {
        // A horizontally flipped face (selfie footage): every x reflected about
        // the frame centre. The fit must stay a proper similarity transform.
        val f = realisticFace()
        val mirrored = f.copy(
            landmarks = f.landmarks.map { it.copy(x = 1080f - it.x) },
            boundingBox = BoundingBox(
                left = 1080 - f.boundingBox.right,
                top = f.boundingBox.top,
                right = 1080 - f.boundingBox.left,
                bottom = f.boundingBox.bottom,
            ),
        )
        val m = RecognitionFaceCrop.transformFor(mirrored, 112)
        assertNotNull("a mirrored face must still align", m)
        assertTrue("must never emit a reflection", m!!.determinant > 0.0)
    }

    @Test
    fun theSpecsFixedSwapWouldHaveProducedADegenerateFit() {
        // Regression guard documenting WHY the mapping changed. Forcing the
        // spec's literal ordering on real device landmarks (LEFT_EYE at the
        // smaller x) inverts the face: the residual explodes from ~1.7 px to
        // ~27 px and the determinant collapses toward zero.
        val leftEye = doubleArrayOf(282.5, 200.8)
        val rightEye = doubleArrayOf(380.1, 201.0)
        val nose = doubleArrayOf(328.4, 248.4)
        val mouthLeft = doubleArrayOf(287.8, 308.6)
        val mouthRight = doubleArrayOf(369.2, 307.9)

        fun maxResidual(pts: Array<DoubleArray>): Double {
            val m = RecognitionFaceCrop.umeyama(pts, tpl)!!
            var r = 0.0
            for (i in 0 until 5) {
                val p = m.apply(pts[i][0], pts[i][1])
                r = maxOf(r, hypot(p[0] - tpl[i][0], p[1] - tpl[i][1]))
            }
            return r
        }

        val measured = maxResidual(arrayOf(leftEye, rightEye, nose, mouthLeft, mouthRight))
        val specLiteral = maxResidual(arrayOf(rightEye, leftEye, nose, mouthRight, mouthLeft))

        assertTrue("measured ordering must fit tightly (~1.7 px), got $measured", measured < 5.0)
        assertTrue("the literal spec ordering must fit badly (~27 px), got $specLiteral", specLiteral > 20.0)
    }

    @Test
    fun upsideDownFace_isRejected_eyesMustBeAboveMouth() {
        val f = face(
            viewerLeftEye = 412.3f to 404.2f,
            viewerRightEye = 498.1f to 399.1f,
            nose = 452.0f to 352.9f,
            viewerLeftMouth = 419.8f to 301.7f,
            viewerRightMouth = 489.5f to 296.4f,
        )
        val p = RecognitionFaceCrop.orderedLandmarks(f)!!
        assertFalse(RecognitionFaceCrop.landmarkOrderIsPlausible(p, f.boundingBox))
    }

    @Test
    fun implausibleInterOcularDistance_isRejected() {
        val box = BoundingBox(380, 270, 530, 440) // 150 px wide
        // eyes 3 px apart => ratio 0.02, far below the 0.15 floor
        val tooClose = face(
            viewerLeftEye = 450f to 301f, viewerRightEye = 453f to 301f,
            nose = 452f to 352f,
            viewerLeftMouth = 419.8f to 404.2f, viewerRightMouth = 489.5f to 399.1f,
            box = box,
        )
        assertFalse(
            RecognitionFaceCrop.landmarkOrderIsPlausible(
                RecognitionFaceCrop.orderedLandmarks(tooClose)!!, box,
            )
        )
        // eyes 300 px apart => ratio 2.0, above the 1.20 ceiling
        val tooFar = face(
            viewerLeftEye = 300f to 301f, viewerRightEye = 600f to 301f,
            nose = 452f to 352f,
            viewerLeftMouth = 419.8f to 404.2f, viewerRightMouth = 489.5f to 399.1f,
            box = box,
        )
        assertFalse(
            RecognitionFaceCrop.landmarkOrderIsPlausible(
                RecognitionFaceCrop.orderedLandmarks(tooFar)!!, box,
            )
        )
    }

    @Test
    fun aPlausibleFaceIsAccepted() {
        val f = realisticFace()
        assertTrue(
            RecognitionFaceCrop.landmarkOrderIsPlausible(
                RecognitionFaceCrop.orderedLandmarks(f)!!, f.boundingBox,
            )
        )
        assertNotNull(RecognitionFaceCrop.transformFor(f, 112))
    }

    // =======================================================================
    // UMEYAMA SIMILARITY TRANSFORM — golden values from the Python reference
    // =======================================================================

    @Test
    fun umeyama_templateOntoItself_isTheIdentity() {
        val src = Array(5) { doubleArrayOf(tpl[it][0], tpl[it][1]) }
        val m = RecognitionFaceCrop.umeyama(src, tpl)!!
        assertEquals(1.0, m.a, 1e-9)
        assertEquals(0.0, m.b, 1e-9)
        assertEquals(0.0, m.tx, 1e-6)
        assertEquals(0.0, m.c, 1e-9)
        assertEquals(1.0, m.d, 1e-9)
        assertEquals(0.0, m.ty, 1e-6)
        assertEquals(1.0, m.determinant, 1e-9)
    }

    @Test
    fun umeyama_recoversAKnownRotationAndScale_exactly() {
        // Golden values from the Python reference: a=+0.303126663 b=+0.110329099
        // tx=-98.349396 c=-0.110329099 d=+0.303126663 ty=+23.193645
        val th = Math.toRadians(20.0)
        val sc = 3.1
        val src = Array(5) {
            val x = tpl[it][0] - 56.0
            val y = tpl[it][1] - 70.0
            doubleArrayOf(
                sc * (x * cos(th) - y * sin(th)) + 400.0,
                sc * (x * sin(th) + y * cos(th)) + 300.0,
            )
        }
        val m = RecognitionFaceCrop.umeyama(src, tpl)!!
        assertEquals(0.303126663, m.a, 1e-6)
        assertEquals(0.110329099, m.b, 1e-6)
        assertEquals(-98.349396, m.tx, 1e-3)
        assertEquals(-0.110329099, m.c, 1e-6)
        assertEquals(0.303126663, m.d, 1e-6)
        assertEquals(23.193645, m.ty, 1e-3)
        // the transform is the exact inverse, so residuals vanish
        for (i in 0 until 5) {
            val p = m.apply(src[i][0], src[i][1])
            assertEquals(tpl[i][0], p[0], 1e-4)
            assertEquals(tpl[i][1], p[1], 1e-4)
        }
    }

    @Test
    fun umeyama_matchesThePythonReferenceOnANoisyRealFace() {
        // Golden values: a=+0.401977420 b=-0.006517156 tx=-124.321648
        //                c=+0.006517156 d=+0.401977420 ty=-72.098022
        // (maxres 1.359 px — a real face is not an exact similarity of the
        //  template, which is precisely why this is a least-squares fit.)
        val src = arr(
            412.3 to 301.7, 498.1 to 296.4, 452.0 to 352.9,
            419.8 to 404.2, 489.5 to 399.1,
        )
        val m = RecognitionFaceCrop.umeyama(src, tpl)!!
        assertEquals(0.401977420, m.a, 1e-6)
        assertEquals(-0.006517156, m.b, 1e-6)
        assertEquals(-124.321648, m.tx, 1e-3)
        assertEquals(0.006517156, m.c, 1e-6)
        assertEquals(0.401977420, m.d, 1e-6)
        assertEquals(-72.098022, m.ty, 1e-3)

        var maxRes = 0.0
        for (i in 0 until 5) {
            val p = m.apply(src[i][0], src[i][1])
            maxRes = maxOf(maxRes, hypot(p[0] - tpl[i][0], p[1] - tpl[i][1]))
        }
        assertEquals("least-squares residual must match the reference", 1.359, maxRes, 1e-2)
    }

    @Test
    fun umeyama_handlesNegativeRotation() {
        // Golden: a=+0.409576029 b=-0.286788195 tx=+5.227865
        //         c=+0.286788195 d=+0.409576029 ty=-75.420738
        val th = Math.toRadians(-35.0)
        val src = Array(5) {
            val x = tpl[it][0] - 56.0
            val y = tpl[it][1] - 70.0
            doubleArrayOf(
                2.0 * (x * cos(th) - y * sin(th)) + 250.0,
                2.0 * (x * sin(th) + y * cos(th)) + 180.0,
            )
        }
        val m = RecognitionFaceCrop.umeyama(src, tpl)!!
        assertEquals(0.409576029, m.a, 1e-6)
        assertEquals(-0.286788195, m.b, 1e-6)
        assertEquals(5.227865, m.tx, 1e-3)
        assertEquals(0.286788195, m.c, 1e-6)
        assertEquals(0.409576029, m.d, 1e-6)
        assertEquals(-75.420738, m.ty, 1e-3)
    }

    // =======================================================================
    // NO REFLECTION
    // =======================================================================

    @Test
    fun transformIsNeverAReflection_determinantStaysPositive() {
        val m = RecognitionFaceCrop.transformFor(realisticFace(), 112)!!
        assertTrue("a similarity transform must not mirror", m.determinant > 0.0)
    }

    @Test
    fun umeyama_onMirroredInput_stillReturnsAProperRotation() {
        // Feed a horizontally mirrored point set. Umeyama's sign fix forbids a
        // reflection, so the best proper-rotation fit comes back with a POSITIVE
        // determinant — it cannot express the mirror, which is exactly the
        // guarantee we want.
        val src = Array(5) { doubleArrayOf(200.0 - tpl[it][0], tpl[it][1]) }
        val m = RecognitionFaceCrop.umeyama(src, tpl)!!
        assertTrue("must never produce a reflection", m.determinant > 0.0)
    }

    @Test
    fun umeyama_scaleIsUniform_onBothAxes() {
        val m = RecognitionFaceCrop.umeyama(
            arr(412.3 to 301.7, 498.1 to 296.4, 452.0 to 352.9, 419.8 to 404.2, 489.5 to 399.1),
            tpl,
        )!!
        // for a similarity transform [[a,b],[c,d]] = s*R, so a == d and b == -c
        assertEquals("a and d must match (uniform scale)", m.a, m.d, 1e-9)
        assertEquals("b must be -c (pure rotation)", m.b, -m.c, 1e-9)
    }

    @Test
    fun umeyama_returnsNullOnDegenerateInput() {
        val coincident = arr(1.0 to 1.0, 1.0 to 1.0, 1.0 to 1.0, 1.0 to 1.0, 1.0 to 1.0)
        val m = RecognitionFaceCrop.umeyama(coincident, tpl)
        // scale falls back to 1.0 on zero variance; either a null or a
        // finite-but-degenerate matrix is acceptable, but it must not be NaN.
        if (m != null) {
            assertTrue(m.a.isFinite() && m.d.isFinite() && m.tx.isFinite() && m.ty.isFinite())
        }
    }

    // =======================================================================
    // OUTPUT SIZE
    // =======================================================================

    @Test
    fun transformMapsLandmarksOntoTheScaledTemplate_at224() {
        val f = realisticFace()
        val m = RecognitionFaceCrop.transformFor(f, 224)!!
        val src = RecognitionFaceCrop.orderedLandmarks(f)!!
        val t224 = RecognitionFaceCrop.templateFor(224)
        // scale doubles relative to the 112 fit
        val m112 = RecognitionFaceCrop.transformFor(f, 112)!!
        assertEquals(m112.a * 2.0, m.a, 1e-6)
        // and the residuals also double
        for (i in 0 until 5) {
            val p = m.apply(src[i][0], src[i][1])
            assertTrue(hypot(p[0] - t224[i][0], p[1] - t224[i][1]) < 3.0)
        }
    }

    @Test
    fun nonPositiveOutputSizeIsRejected() {
        assertNull(RecognitionFaceCrop.transformFor(realisticFace(), 0))
        assertNull(RecognitionFaceCrop.transformFor(realisticFace(), -112))
    }
}
